platform :ios, '7.0'
target 'FyhNewProj' do
    pod 'RongCloudIM/IMLib', '~> 2.8.3’
    pod 'RongCloudIM/IMKit', '~> 2.8.3’
    pod 'ReactiveCocoa', '~> 2.5'
    pod 'JPush', '3.0.2'
    pod 'UMengAnalytics-NO-IDFA'
    pod 'IQKeyboardManager'
end
